### PR TITLE
Update for changed property name.

### LINKED ISSUE #9: Model shows on main menu, but fails to load in-game
Thinking, related to the [latest update](https://store.steampowered.com/news/app/892970/view/3680050666246567445).

<details>

<summary>Stack trace:</summary> 

```
MissingMethodException: long ZDOID.get_userID()
  at System.Collections.Generic.List`1[T].FindIndex (System.Int32 startIndex, System.Int32 count, System.Predicate`1[T] match) [0x0003b] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.Collections.Generic.List`1[T].FindIndex (System.Predicate`1[T] match) [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at ValheimPlayerModels.PlayerModel+<LoadAvatar>d__37.MoveNext () [0x0025f] in <e83812d156da4d26b29b6a16a8aa6b35>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <80fe1a4e36fe44618284312cb721a597>:0 
```

</details>

Bit of poking around with, looking at the assemblies with dnSpy, seems like they might've renamed `userID` to `UserID`, so [the index lookup](https://github.com/Ikeiwa/ValheimPlayerModels/blob/89407ff240040b527a6dbab1194739c97d950f4e/PluginSolution/PlayerModel.cs#L236) fails as it tries to call a non-existent accessor?

So really, the `Valheim.GameLibs` stuff needs to be updated, and carried through here, or to otherwise handle "publicization" of the game assemblies?

### PR DESCRIPTION
**Pull request by dresklaw**
Fixes #9

### CODE REVIEW

**Comment by dresklaw** [comment]
Guess I'll throw this here, in case others find themselves here, and want to use this: the built DLL (in the .zip), and sha512sum and SSH key signing, for paranoia:

[ValheimPlayerModels.zip](https://github.com/Ikeiwa/ValheimPlayerModels/files/11782132/ValheimPlayerModels.zip)

<details>
<summary>The paranoia things</summary>

Not sure of their actual utility, but seems like a good idea.

[ValheimPlayerModels.zip.sig.txt](https://github.com/Ikeiwa/ValheimPlayerModels/files/11782134/ValheimPlayerModels.zip.sig.txt)

```
$ sha512sum.exe -b ValheimPlayerModels.zip ValheimPlayerModels.dll ValheimPlayerModels.dll.sig ValheimPlayerModels.zip.sig
b59b9db868e2394aad0466f9a6eb70e8256b6bd4248aa846567e9d7b6f80f05fafacf8d9087efcc5b602f4a5436c531c5c10a377d6b6f6e8b3a9602cea03dd52 *ValheimPlayerModels.zip
8f4412236ee88d75222848f2e3f56d6739f920068894bb0ea6a57d0a4ed4993cbf540e38037b15337a0d9e40ed8b10083216033276bc366bd6059eae85e25624 *ValheimPlayerModels.dll
9128db34aebb898f652dd31b520852f64e0c6fd060eb0a65fe79103d21bcb4d0ff0ace784a10036108e7f5695b575a873df169c3b8b1228fba51f8d1e1c8b75c *ValheimPlayerModels.dll.sig
67a18aca127bb738a13c5549f6b676b66503abe90b79e0702640c5237e66b2719ec0a547ff07c27aa3aee67f29029f2c5692f4a448d468da3b621c26df1172a3 *ValheimPlayerModels.zip.sig
```

Signing's been done with my present Github SSH key. The public key of the pair used for signing can be obtained from https://api.github.com/users/dresklaw/ssh_signing_keys , specifically, `122361`.

Should be able to verify the couple of signatures with something like:

```
$ ssh-keygen.exe -Y check-novalidate -n file -f ~/.ssh/id_rsa.pub -s ValheimPlayerModels.zip.sig.txt < ValheimPlayerModels.zip
Good "file" signature with RSA key SHA256:tkXg1meWn04n0hDJeSTJJcOSFDB2+kZYAVjZUrqCyxU
```

and after extracting the DLL:

```
$ ssh-keygen.exe -Y check-novalidate -n file -f ~/.ssh/id_rsa.pub -s ValheimPlayerModels.dll.sig < ValheimPlayerModels.dll
Good "file" signature with RSA key SHA256:tkXg1meWn04n0hDJeSTJJcOSFDB2+kZYAVjZUrqCyxU
```

with `~/.ssh/id_rsa.pub` being the path instead of wherever my public key was placed.

... shrug?

</details>

**Comment by bluejorts** [comment]
Thanks for building this, fixed on latest Valheim for me now. @Ikeiwa should merge <3

**Comment by Ikeiwa** [comment]
Wow I can't thank you enough! I don't have the time anymore to work on this mod so thanks a lot @dresklaw for fixing it ❤️.
I'll update the mod on nexus and thunderstore soon.

**Comment by IceOfWraith** [comment]
Soon™

**Comment by AartHauk** [comment]
Soon™

**Pull request merged**
